import { emailTransporter } from '../config/mailer';
import { env } from '../config/env';
import { logger } from '../config/logger';

interface SendEmergencyEmailOptions {
  to: string;
  contactName: string;
  userName: string;
  alertCode: string;
  latitude: number;
  longitude: number;
  message?: string;
}

export async function sendEmergencyEmail(options: SendEmergencyEmailOptions): Promise<void> {
  const { to, contactName, userName, alertCode, latitude, longitude, message } = options;
  const mapsLink = `https://maps.google.com/?q=${latitude},${longitude}`;

  try {
    await emailTransporter.sendMail({
      from: env.SMTP_FROM,
      to,
      subject: `Emergency alert ${alertCode}`,
      html: `
        <p>Dear ${contactName},</p>
        <p>${userName} triggered an emergency alert.</p>
        <p><strong>Alert Code:</strong> ${alertCode}</p>
        <p><strong>Location:</strong> <a href="${mapsLink}">${latitude}, ${longitude}</a></p>
        ${message ? `<p><strong>Message:</strong> ${message}</p>` : ''}
      `,
    });
  } catch (error) {
    logger.warn('Emergency email delivery failed', { to, alertCode, error });
  }
}

interface PoliceAlertEmailOptions {
  incidentId: string;
  incidentType: string;
  latitude: number;
  longitude: number;
  score: number;
  likes: number;
  commentCount: number;
  createdAt: Date;
  description?: string | null;
}

export async function sendPoliceAlertEmail(options: PoliceAlertEmailOptions): Promise<void> {
  if (!env.POLICE_ALERT_EMAIL) {
    logger.warn('Skipping police alert email because POLICE_ALERT_EMAIL is not configured');
    return;
  }

  const {
    incidentId,
    incidentType,
    latitude,
    longitude,
    score,
    likes,
    commentCount,
    createdAt,
    description,
  } = options;

  try {
    await emailTransporter.sendMail({
      from: env.SMTP_FROM,
      to: env.POLICE_ALERT_EMAIL,
      subject: '[CRITICAL ALERT] High-Density Incident Zone Detected — Immediate Attention Required',
      html: `
        <h2 style="color:#dc2626;">High-Density Incident Zone Alert</h2>
        <p>This is an automated alert from the Disaster Relief Response System.</p>
        <p>An area has been flagged as a <strong>high-density incident zone</strong> based on aggregated community reports.</p>
        <table style="border-collapse:collapse;width:100%;margin:16px 0;">
          <tr><td style="padding:8px;font-weight:bold;background:#f3f4f6;">Incident ID</td><td style="padding:8px;">${incidentId}</td></tr>
          <tr><td style="padding:8px;font-weight:bold;background:#f3f4f6;">Type</td><td style="padding:8px;">${incidentType}</td></tr>
          <tr><td style="padding:8px;font-weight:bold;background:#f3f4f6;">Coordinates</td><td style="padding:8px;">${latitude}, ${longitude}</td></tr>
          <tr><td style="padding:8px;font-weight:bold;background:#f3f4f6;">Incident Score</td><td style="padding:8px;">${score} (Likes: ${likes}, Comments: ${commentCount})</td></tr>
          <tr><td style="padding:8px;font-weight:bold;background:#f3f4f6;">Reported At</td><td style="padding:8px;">${createdAt.toISOString()}</td></tr>
          <tr><td style="padding:8px;font-weight:bold;background:#f3f4f6;">Description</td><td style="padding:8px;">${description ?? 'No description provided'}</td></tr>
        </table>
        <p>Please dispatch personnel to investigate and respond to this location immediately.</p>
        <p style="color:#6b7280;font-size:12px;">This email was automatically generated by the Disaster Relief Response System. Do not reply.</p>
      `,
    });
  } catch (error) {
    logger.error('Police alert email delivery failed', { incidentId, error });
  }
}
